# Generated by Django 3.2.3 on 2023-09-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmiData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emi_amount', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('is_paid', models.BooleanField()),
            ],
            options={
                'db_table': 'emi_data',
            },
        ),
        migrations.CreateModel(
            name='LoanData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.IntegerField()),
                ('loan_type', models.CharField(choices=[('CAR', 'Car'), ('HOM', 'Home'), ('EDU', 'Education'), ('PER', 'Personal')], max_length=3)),
                ('interest', models.IntegerField()),
                ('term_period', models.IntegerField()),
                ('disbursement_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'loan_data',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('annual_income', models.IntegerField()),
                ('credit_score', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='UQ_name_email'),
        ),
        migrations.AddField(
            model_name='loandata',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='API.users'),
        ),
        migrations.AddField(
            model_name='emidata',
            name='loan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='API.loandata'),
        ),
        migrations.AddConstraint(
            model_name='loandata',
            constraint=models.UniqueConstraint(fields=('user_id', 'loan_type', 'loan_amount', 'disbursement_date'), name='UQ_user_id_loan_type_loan_amount_date'),
        ),
        migrations.AddConstraint(
            model_name='emidata',
            constraint=models.UniqueConstraint(fields=('loan_id', 'date', 'emi_amount'), name='UQ_loan_id_date_emi_amount'),
        ),
    ]
